# tasks file for hostname
---
- name: update the hostname - hostname module
  hostname:
    name: "{{ hostname_hostname_short }}"
  tags:
    - configuration
    - hostname
    - hostname-update-hostname

- name: update the hostname - /etc/hostname file
  template:
    src: etc/hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - hostname
    - hostname-update-hostname
    - hostname-update-hostname-file

- name: update the hostname - /etc/hosts file
  template:
    src: etc/hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - hostname
    - hostname-update-hosts-file
